### ISSUE TITLE
24 Hour Notice

### ISSUE THREAD

**Issue by Greenlio** [Jude-Gideon/Blooket-Hacks#80]
This repository is in blatant violation of the [Stewart Private License](https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE). If the repostitory is not privated within 24 hours, we will be forced to submit a DMCA request, within our rights, to GitHub to avoid any further damages.

Blatantly violating files include:
- gui.js

I swear, under penalty of perjury, that the information in this notification, intended to offer a chance for the user to fix their mistake, is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

Green & the Council of Ben Stewart

**Comment by Jude-Gideon** [comment]
sorry didn't know it was stolen but taken down.

**Comment by Jude-Gideon** [comment]
is what i did fine i'm unable to delete the file i can only remove code on my phone

**Comment by Greenlio** [comment]
> is what i did fine i'm unable to delete the file i can only remove code on my phone

yes

**Comment by Jude-Gideon** [comment]
alright, i apologize for this inconvenience
