### ISSUE TITLE
BUG: Gui

### ISSUE THREAD

**Issue by UmbraAstro** [Jude-Gideon/Blooket-Hacks#81]
Umm everyone can still have access to the gui it’s still there u can just go in history idk if u know that

**Comment by Jude-Gideon** [comment]
i'm going to delete then, had to remove it for a reason.

**Comment by Jude-Gideon** [comment]
sorry man.

**Comment by Jude-Gideon** [comment]
i plan to make a new one soon

**Comment by UmbraAstro** [comment]
alright that’s fine how do u make the gui I can make the hacks just not the gui how did u make those?

**Comment by Jude-Gideon** [comment]
the code is obfuscated for the reason people dont just rip off my hacks and more, if i were to tell people how to make hacks and guis there would be no point for me to obfuscate my code.

**Comment by UmbraAstro** [comment]
But then why did the dmca take it down was the gui Minesrafts?

**Comment by Jude-Gideon** [comment]
no it was the fact i didn't know my gui was almost identical to his mobile gui.
