### ISSUE TITLE
TRY TO ACTUALLY MAKE IT WROK

### ISSUE THREAD

**Issue by gite884** [Jude-Gideon/Blooket-Hacks#82]

**Comment by Jude-Gideon** [comment]
?

**Comment by Jude-Gideon** [comment]
you're using a suggestion template as an issue and proving me no information on what doesn't work...

**Comment by gite884** [comment]
Oh wait it works
now THANK YOU SO MUCH

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Jude-Gideon** [comment]
next time use an issue template and tell me what's wrong, but you're welcome

**Comment by gite884** [comment]
IT WROKS NOW THAN YOU


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Wilke000** [comment]
Caps lock :P
