### ISSUE TITLE
Umm,m

### ISSUE THREAD

**Issue by UmbraAstro** [Jude-Gideon/Blooket-Hacks#84]

**Comment by UmbraAstro** [comment]
![885A10EE-D9E3-4462-872B-7639326311A0](https://user-images.githubusercontent.com/121777559/213603601-2cf4ac7c-35e5-4c22-8ac1-efd701c62404.jpeg)

**Comment by Jude-Gideon** [comment]
can you please shut the fuck up and quit spamming me with issues about my gui you're annoying

**Comment by Jude-Gideon** [comment]
it's gone for a reason

**Comment by Jude-Gideon** [comment]
the gui will be re made later

**Comment by UmbraAstro** [comment]
No I’m not stupid I know why it’s gone cause the Dmca made you take it down I’m pointing out people can still see it just like people can unobfuscate ur code
