### ISSUE TITLE
How to spam the Ice Monsters pack?

### ISSUE THREAD

**Issue by RandyPlayzMC** [Jude-Gideon/Blooket-Hacks#86]
I don't know how to use the spam boxes on the Ice Monsters pack

**Comment by Jude-Gideon** [comment]
just type in the name of the box it shows an example at the top

**Comment by Wilke000** [comment]
Put in “Ice Monster” (No s at the end of monster)

**Comment by Jude-Gideon** [comment]
^^^

**Comment by Wilke000** [comment]
Jude could you make it so that if you put Ice Monsters or Ice Monster it would do the same thing?

**Comment by Jude-Gideon** [comment]
i don't know i'll try later
