### ISSUE TITLE
Add tokens fix

### ISSUE THREAD

**Issue by ThePineappleMan2013** [Jude-Gideon/blooket-hacks#88]
## What file is causing the issue?
global add rewards
## What issue is being caused by this file?
it says there was error getting bonus data
## In what way was this file ran?
through javascript:   and inspect console

**Comment by Cruise321** [comment]
It doesn't work. It just says ''Error getting bonus data''

**Comment by Jude-Gideon** [comment]
Removed bonus URL and made it just go through adding rewards.
